FROM mysql:8.0

LABEL maintainer="NorthernBytes Ab Oy <contact@nbts.fi>"

CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password"]